### ISSUE TITLE
Enforce minimal length for passwords

### ISSUE THREAD

**Issue by m-rey** [acipm/kibicara#15]
Passwords have to meet a minimal length requirement to improve security.

**Comment by hagenest** [comment]
What minimum would be sufficient? 8 may be kinda low if you don't force people to use special characters and/or major and minor case.

**Comment by m-rey** [comment]
Afaik you shouldn't force people to use special characters or similar. NIST recommends a minimum length of 8 characters.

**Comment by hagenest** [comment]
wow, missclicks are real
