### ISSUE TITLE
Some thoughts about testing

### ISSUE THREAD

**Issue by m-rey** [acipm/kibicara#17]
* How should we structure tests?
* Tests shouldn't interfere with each other. How should we handle tests that need databases? Delete the database after every test? Mock the database?
* Many tests require being logged in. Instead of writing the login and register code for each test, we can use [pytest fixtures](https://www.tutorialspoint.com/pytest/pytest_fixtures.htm).

**Comment by maikeMai** [comment]
We could use an empty database which is filled by the tests and thrown away at the end... This way we could automate the whole functionality and try out everything.

**Comment by m-rey** [comment]
Each test should be isolated from each other. Maybe using a fixture to create a database before and destroy it after the test would guarantee that.
