### ISSUE TITLE
With which python versions do we want to run tests?

### ISSUE THREAD

**Issue by maikeMai** [acipm/kibicara#29]
In https://github.com/acipm/kibicara/pull/10/checks?check_run_id=845049106, the tests failed, because the github action runner didn't install python3.7. Before, it worked most of the time.

I'm not sure if we can trivially install both python versions - at least it wouldn't be very beautiful.

Isn't it enough if we run the tests with python3.7? 3.6 shouldn't work anyway (I wonder why the tests work for 3.6), and if 3.7 works, 3.8 probably works as well.

What do you think?

**Comment by m-rey** [comment]
`tox` is able to (and even designed to) test using different python versions. I think that there should be a way to install and use multiple python versions with the GitHub action runner.
As a quick workaround we could limit testing to python 3.7, but this shouldn't be a permanent "fix".

**Comment by maikeMai** [comment]
The tests are run only with python 3.8 for now: https://github.com/acipm/kibicara/pull/30#issuecomment-655469588

If this topic is important to anyone, feel free to take over #30 and finish it :)

Closing this for now, just reopen it if you want to work on this.
