### ISSUE TITLE
Limit possible characters for hood names

### ISSUE THREAD

**Issue by maikeMai** [acipm/kibicara#40]
We want to limit hood names to consist out of lower case ascii letters and numbers, so [a-z0-9].

limitations we encounter:

- there are certain restrictions for the localpart of email addresses.
- sanitizing user input is important to limit attack surface; this is a user input.

to be researched: symbols which are allowed in email localparts, e.g. `-_+` (+ is already a special case and gets interpreted, should be excluded)

**Comment by maikeMai** [comment]
Apart from that, we should limit possible hood names, because if it's possible to receive mail for `root@kibicara.net` as an admin, we have a security problem:

https://webmasters.stackexchange.com/questions/104811/is-there-any-list-of-email-addresses-reserved-because-of-security-concerns-for-a#105020

**Comment by m-rey** [comment]
Duplicate of #16

Please add the info there :)
